# Generated by Django 2.0.2 on 2018-02-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_host', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('place', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('cash_only', models.BooleanField()),
                ('event', models.TextField()),
                ('contents', models.ManyToManyField(to='poster_manager.Content')),
                ('hosts', models.ManyToManyField(to='poster_manager.Host')),
            ],
        ),
    ]
